### ISSUE TITLE
UWP ListView with odata

### ISSUE THREAD

**Issue by yxylpj** [brookshi/XPHttp#1]
Hello
I want to use xphttp on odata binding,  my code below, but I can not work, how may I do?
thanks!

**## uwp client code:**
`XPHttpClient.DefaultClient.HttpConfig.SetBaseUrl("http://localhost:60698/").SetUseHttpCache(false).ApplyConfig();
var httpParam = XPHttpClient.DefaultClient.RequestParamBuilder;
 var response = await XPHttpClient.DefaultClient.GetAsync<IEnumerable<ExpInfo>>("odata/ExpInfos", httpParam);
 IEnumerable<ExpInfo> dbOdataList = response
odataListView.ItemsSource = dbOdataList;`

**## service code:**
`public class ExpInfosController : ODataController
    {
        private static ODataValidationSettings _validationSettings = new ODataValidationSettings();

```
    // GET: odata/ExpInfos
    public IHttpActionResult GetExpInfos(ODataQueryOptions<ExpInfo> queryOptions)
    {
        // validate the query.
        try
        {
            queryOptions.Validate(_validationSettings);
        }
        catch (ODataException ex)
        {
            return BadRequest(ex.Message);
        }
        List<ExpInfo> expInfos = new List<ExpInfo>();
        ExpInfo[] exps =
        {
            new ExpInfo { ExpName="申通快递",PhoneNo="95543", ImageUrl = "http://cdn.kuaidi100.com/images/frame/baidu/all/st.gif?version=201504201500" },
            new ExpInfo { ExpName="顺丰速运",PhoneNo="95338",ImageUrl = "http://cdn.kuaidi100.com/images/frame/baidu/all/sf.gif?version=201504201500" },
            new ExpInfo { ExpName="韵达快递",PhoneNo="95546",ImageUrl = "http://cdn.kuaidi100.com/images/frame/baidu/all/yd.gif?version=201504201500" },
            new ExpInfo { ExpName="圆通速递",PhoneNo="95554",ImageUrl = "http://cdn.kuaidi100.com/images/frame/baidu/all/yt.gif?version=201504201500" },
            new ExpInfo { ExpName="中通速递",PhoneNo="95311 / 4008-270-270",ImageUrl = "http://cdn.kuaidi100.com/images/frame/baidu/all/zt.gif?version=201504201500" },
            new ExpInfo { ExpName="EMS快递", PhoneNo="11183", ImageUrl = "http://cdn.kuaidi100.com/images/frame/baidu/all/ems.gif?version=201504201500" },
            new ExpInfo { ExpName="天天快递", PhoneNo="4001-888-888", ImageUrl = "http://cdn.kuaidi100.com/images/frame/baidu/all/tt.gif?version=201504201500" },
        };
        expInfos.AddRange(exps);
        for (int i = 0; i < 10000; i++)
        {
            ExpInfo expInfo = new UWPSample.ViewModels.ExpInfo();
            expInfo.ID = Guid.NewGuid();
            expInfo.PhoneNo = i.ToString().PadLeft(8, '0'); 
            expInfo.ExpName = "ExpInfo_" + i;
            expInfo.ImageUrl = "http://cdn.kuaidi100.com/images/frame/baidu/all/tt.gif?version=201504201500";
            expInfos.Add(expInfo);
        }
        return Ok<IEnumerable<ExpInfo>>(expInfos);
    }
```

}`

**Comment by brookshi** [comment]
var response = await XPHttpClient.DefaultClient.GetAsync>("odata/ExpInfos", httpParam);
is response correctly here?
try use List instead of IEnumerable

**Comment by yxylpj** [comment]
I'm sorry, the client code write error, the code is below:

`var response = await XPHttpClient.DefaultClient.GetAsync<IEnumerable<ExpInfo>>("odata/ExpInfos", httpParam);`

but, response null.

if I use code below, it response correct data, but I don't know how to bind datasoure to the listview async.

`var response = await XPHttpClient.DefaultClient.GetAsync<object>("odata/ExpInfos", httpParam);`

**Comment by brookshi** [comment]
.. github hide <>
try List<>

**Comment by brookshi** [comment]
could you capture response string and send to me? i will check it when i go back home

**Comment by yxylpj** [comment]
ok, I send project to you after a moment.

**Comment by brookshi** [comment]
may caused by `Ok<IEnumerable<ExpInfo>>(expInfos);` why not return expInfos directly.

**Comment by yxylpj** [comment]
return expInfos directly also ok, but client get the same result.
my sample is below
[https://setup.aserweb.com/UWPSample.zip](url)

**Comment by brookshi** [comment]
add wechat: iwxiaot
